spring:
  datasource:
    url: jdbc:h2:file:~/h2/h2db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
  mvc:
    static-path-pattern: classpath:static/
    hiddenmethod.filter.enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG